# Generated by Django 3.1.1 on 2021-03-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210304_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='received_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
