# Generated by Django 3.1.1 on 2021-03-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210305_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
