# Generated by Django 3.1.7 on 2021-03-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210305_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ammount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
