# Generated by Django 3.1.7 on 2021-03-05 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20210306_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_csv',
        ),
        migrations.AddField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
