# Generated by Django 3.1.7 on 2021-03-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20210306_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='sup_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
