# Generated by Django 3.1.7 on 2021-03-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210307_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='issued_to',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_in_quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_out_quantity',
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
